endpoint: https://jira.dev.bbc.co.uk
unixproxy: /usr/local/var/client-cert-proxy-stunnel.sock
user: kieran.bamforth@bbc.co.uk
project: ORBITEN
custom-commands:

    - name : mine
      help: Display issues assigned to me
      script: |-
          {{jira}} list --query "resolution = unresolved and assignee=currentuser() ORDER BY created"

    - name: browser
      help: Open an issue in the browser
      args:
        - name: number
          required: true
      options:
        - name: project
          short: p
          default: $JIRA_PROJECT
      script: |-
          {{jira}} browse {{options.project}}-{{args.number}}
      aliases:
        - br

    - name: sprint
      help: Display issues for active sprint
      options:
        - name: project
          short: p
          default: $JIRA_PROJECT
      script: |-
          {{jira}} list --query "sprint in openSprints() and type != epic and resolution = unresolved and project={{options.project}} ORDER BY rank asc, created"
      aliases:
        - sp

    - name: watching
      help: Display issues I'm watching
      options:
      script: |-
          {{jira}} list --query "watcher = currentUser()"
      aliases:
        - wa

    - name: created
      help: Display issues that have been created
      options:
        - name: count
          short: c
          default: 1w
        - name: project
          short: p
          default: $JIRA_PROJECT
      script: |-
        {{jira}} list --query "created >= -{{options.count}} and project = {{options.project}}"
      aliases:
        - cr

    - name: search
      help: Search for issues
      options:
        - name: project
          short: p
          default: $JIRA_PROJECT
      args:
        - name: text
          required: true
      script: |-
        {{jira}} list --query "text ~ {{args.text}} and project = {{options.project}}"
      aliases:
        - se

    - name: label
      help: List issues with labels
      options:
        - name: project
          short: p
          default: $JIRA_PROJECT
      args:
        - name: labels
          required: true
      script: |-
        {{jira}} list --query "labels in ( {{args.labels}} ) and project = {{options.project}}"
      aliases:
        - la

    - name: innersource
      help: List issues with innersource labels that are not complete
      script: |-
        {{jira}} list --query "labels in (innersource) and project = {{options.project}} and statusCategory != done order by updatedDate desc"
      aliases:
        - is

    - name: commentissue
      help: Comment on an issue
      options:
        - name: project
          short: p
          default: $JIRA_PROJECT
      args:
        - name: number
          required: true
      script: |-
        {{jira}} comment {{options.project}}-{{args.number}}
      aliases:
        - co

    - name: backlogissues
      help: List issues in the backlog
      options:
        - name: project
          short: p
          default: $JIRA_PROJECT
      script: |-
        {{jira}} list --query "project = ORBITEN AND sprint is EMPTY and statusCategory = 'To Do'"
      aliases:
        - bl

